name: Build Gradle

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run build and tests with Gradle wrapper
        run: ./gradlew test build

      - name: Publish test report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          annotate_notice: true
          detailed_summary: true

      - name: Upload all artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jar
          path: pnx/loader/build/libs/LuckPerms-PNX-*.jar

      - name: Upload standalone artifact
        uses: actions/upload-artifact@v4
        with:
          name: standalone-binary
          path: standalone/loader/build/libs/LuckPerms-Standalone-*.jar

      - name: Release latest build
        uses: Xotl/cool-github-releases@v1
        if: success() && github.repository == 'PowerNukkitX/PowerNukkitX' && contains(github.ref_name, 'master')
        with:
          mode: update
          isPrerelease: false
          tag_name: snapshot
          release_name: "Latest Snapshot"
          body_mrkdwn: |
            This is the **latest version of LuckPerms-PNX**, built from the latest source. 
            (_Please note that the date on GitHub might appear outdated due to certain limitations._)
            **Corresponding commit:** <https://github.com/powernukkitx-bundle/luckperms/commit/${{ github.sha }}>_
            
            > [!NOTE]
            > If you encounter any issues, please report them directly on our [Discord](https://discord.gg/apwd7uauZg) or in the [GitHub Issues](https://github.com/powernukkitx/powernukkitx/issues) tab.
            The file is a zip file. The plugin jar is inside that zip file.
          github_token: ${{ secrets.GITHUB_TOKEN }}